//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.02 at 10:11:22 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardPointInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardPointInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EarnedPoint" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="UsedPoint" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="CampaignPoint" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AvaliablePoint" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardPointInfo", propOrder = {
    "earnedPoint",
    "usedPoint",
    "campaignPoint",
    "avaliablePoint"
})
public class CardPointInfo {

    @XmlElement(name = "EarnedPoint", required = true)
    protected BigDecimal earnedPoint;
    @XmlElement(name = "UsedPoint", required = true)
    protected BigDecimal usedPoint;
    @XmlElement(name = "CampaignPoint", required = true)
    protected BigDecimal campaignPoint;
    @XmlElement(name = "AvaliablePoint", required = true)
    protected BigDecimal avaliablePoint;

    /**
     * Gets the value of the earnedPoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEarnedPoint() {
        return earnedPoint;
    }

    /**
     * Sets the value of the earnedPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEarnedPoint(BigDecimal value) {
        this.earnedPoint = value;
    }

    /**
     * Gets the value of the usedPoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUsedPoint() {
        return usedPoint;
    }

    /**
     * Sets the value of the usedPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUsedPoint(BigDecimal value) {
        this.usedPoint = value;
    }

    /**
     * Gets the value of the campaignPoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCampaignPoint() {
        return campaignPoint;
    }

    /**
     * Sets the value of the campaignPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCampaignPoint(BigDecimal value) {
        this.campaignPoint = value;
    }

    /**
     * Gets the value of the avaliablePoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvaliablePoint() {
        return avaliablePoint;
    }

    /**
     * Sets the value of the avaliablePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvaliablePoint(BigDecimal value) {
        this.avaliablePoint = value;
    }

}
