//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.29 at 09:00:37 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardLimits complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardLimits"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{Smartsoft.Integration.Services}ServiceResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UsedLimitDetailObj" type="{Smartsoft.Integration.Services}UsedLimitDetail" minOccurs="0"/&gt;
 *         &lt;element name="LimitDetailList" type="{Smartsoft.Integration.Services}ArrayOfLimitDetail" minOccurs="0"/&gt;
 *         &lt;element name="BalanceDetailObj" type="{Smartsoft.Integration.Services}BalanceDetail" minOccurs="0"/&gt;
 *         &lt;element name="RealCardLimitDetailObj" type="{Smartsoft.Integration.Services}RealCardLimitDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardLimits", propOrder = {
    "usedLimitDetailObj",
    "limitDetailList",
    "balanceDetailObj",
    "realCardLimitDetailObj"
})
public class CardLimits
    extends ServiceResponse
{

    @XmlElement(name = "UsedLimitDetailObj")
    protected UsedLimitDetail usedLimitDetailObj;
    @XmlElement(name = "LimitDetailList")
    protected ArrayOfLimitDetail limitDetailList;
    @XmlElement(name = "BalanceDetailObj")
    protected BalanceDetail balanceDetailObj;
    @XmlElement(name = "RealCardLimitDetailObj")
    protected RealCardLimitDetail realCardLimitDetailObj;

    /**
     * Gets the value of the usedLimitDetailObj property.
     * 
     * @return
     *     possible object is
     *     {@link UsedLimitDetail }
     *     
     */
    public UsedLimitDetail getUsedLimitDetailObj() {
        return usedLimitDetailObj;
    }

    /**
     * Sets the value of the usedLimitDetailObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsedLimitDetail }
     *     
     */
    public void setUsedLimitDetailObj(UsedLimitDetail value) {
        this.usedLimitDetailObj = value;
    }

    /**
     * Gets the value of the limitDetailList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLimitDetail }
     *     
     */
    public ArrayOfLimitDetail getLimitDetailList() {
        return limitDetailList;
    }

    /**
     * Sets the value of the limitDetailList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLimitDetail }
     *     
     */
    public void setLimitDetailList(ArrayOfLimitDetail value) {
        this.limitDetailList = value;
    }

    /**
     * Gets the value of the balanceDetailObj property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceDetail }
     *     
     */
    public BalanceDetail getBalanceDetailObj() {
        return balanceDetailObj;
    }

    /**
     * Sets the value of the balanceDetailObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceDetail }
     *     
     */
    public void setBalanceDetailObj(BalanceDetail value) {
        this.balanceDetailObj = value;
    }

    /**
     * Gets the value of the realCardLimitDetailObj property.
     * 
     * @return
     *     possible object is
     *     {@link RealCardLimitDetail }
     *     
     */
    public RealCardLimitDetail getRealCardLimitDetailObj() {
        return realCardLimitDetailObj;
    }

    /**
     * Sets the value of the realCardLimitDetailObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealCardLimitDetail }
     *     
     */
    public void setRealCardLimitDetailObj(RealCardLimitDetail value) {
        this.realCardLimitDetailObj = value;
    }

}
