//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.21 at 09:26:50 PM IST 
//


package com.mycardsolutions.webservice.soapdto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardDetailInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardDetailInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CardDci" type="{Smartsoft.Integration.Services}CardDci"/&gt;
 *         &lt;element name="IsBusiness" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IssuingFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="TtlHstBalCurr" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="TtlCrdBalCurr" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="OrderAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ChipBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="PinRetryCount" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="OfflinePin" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="EmbossDate" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="LogoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CourierStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastPinTryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OldCardNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardStatChangeDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Atc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RemainingLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CashLimitRatio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Cvv2RetryCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BlockedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BlockedTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardUpdateUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardCancelReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PersonalizationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EnrollmentNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FinancialType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastTxnDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastTxnTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastTxnAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FirstUsageDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CloseDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RenewalDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BankingCustomerNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardStatCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardSubStatCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardStatDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MainCardNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmbossName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmbossName2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardBrand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardProductId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardBranch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BarcodeNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardDetailInfo", propOrder = {
    "cardDci",
    "isBusiness",
    "issuingFee",
    "ttlHstBalCurr",
    "ttlCrdBalCurr",
    "orderAmount",
    "chipBalance",
    "pinRetryCount",
    "offlinePin",
    "embossDate",
    "logoCode",
    "courierStatus",
    "lastPinTryDate",
    "oldCardNo",
    "cardStatChangeDate",
    "atc",
    "expiryDate",
    "remainingLimit",
    "cashLimitRatio",
    "cvv2RetryCount",
    "blockedDate",
    "blockedTime",
    "cardUpdateUser",
    "cardCancelReason",
    "personalizationDate",
    "enrollmentNo",
    "financialType",
    "lastTxnDate",
    "lastTxnTime",
    "lastTxnAmount",
    "firstUsageDate",
    "closeDate",
    "renewalDate",
    "bankingCustomerNo",
    "cardType",
    "cardNo",
    "cardStatCode",
    "cardSubStatCode",
    "cardStatDescription",
    "mainCardNo",
    "embossName",
    "embossName2",
    "cardBrand",
    "cardProductName",
    "cardProductId",
    "cardBranch",
    "customerNo",
    "cardLevel",
    "accountNo",
    "barcodeNo"
})
public class CardDetailInfo {

    @XmlElement(name = "CardDci", required = true)
    @XmlSchemaType(name = "string")
    protected CardDci cardDci;
    @XmlElement(name = "IsBusiness")
    protected boolean isBusiness;
    @XmlElement(name = "IssuingFee", required = true)
    protected BigDecimal issuingFee;
    @XmlElement(name = "TtlHstBalCurr", required = true)
    protected BigDecimal ttlHstBalCurr;
    @XmlElement(name = "TtlCrdBalCurr", required = true)
    protected BigDecimal ttlCrdBalCurr;
    @XmlElement(name = "OrderAmount", required = true)
    protected BigDecimal orderAmount;
    @XmlElement(name = "ChipBalance", required = true)
    protected BigDecimal chipBalance;
    @XmlElement(name = "PinRetryCount")
    protected short pinRetryCount;
    @XmlElement(name = "OfflinePin")
    protected short offlinePin;
    @XmlElement(name = "EmbossDate")
    protected long embossDate;
    @XmlElement(name = "LogoCode")
    protected String logoCode;
    @XmlElement(name = "CourierStatus")
    protected String courierStatus;
    @XmlElement(name = "LastPinTryDate")
    protected String lastPinTryDate;
    @XmlElement(name = "OldCardNo")
    protected String oldCardNo;
    @XmlElement(name = "CardStatChangeDate")
    protected String cardStatChangeDate;
    @XmlElement(name = "Atc")
    protected String atc;
    @XmlElement(name = "ExpiryDate")
    protected String expiryDate;
    @XmlElement(name = "RemainingLimit")
    protected String remainingLimit;
    @XmlElement(name = "CashLimitRatio")
    protected String cashLimitRatio;
    @XmlElement(name = "Cvv2RetryCount")
    protected String cvv2RetryCount;
    @XmlElement(name = "BlockedDate")
    protected String blockedDate;
    @XmlElement(name = "BlockedTime")
    protected String blockedTime;
    @XmlElement(name = "CardUpdateUser")
    protected String cardUpdateUser;
    @XmlElement(name = "CardCancelReason")
    protected String cardCancelReason;
    @XmlElement(name = "PersonalizationDate")
    protected String personalizationDate;
    @XmlElement(name = "EnrollmentNo")
    protected String enrollmentNo;
    @XmlElement(name = "FinancialType")
    protected String financialType;
    @XmlElement(name = "LastTxnDate")
    protected String lastTxnDate;
    @XmlElement(name = "LastTxnTime")
    protected String lastTxnTime;
    @XmlElement(name = "LastTxnAmount")
    protected String lastTxnAmount;
    @XmlElement(name = "FirstUsageDate")
    protected String firstUsageDate;
    @XmlElement(name = "CloseDate")
    protected String closeDate;
    @XmlElement(name = "RenewalDate")
    protected String renewalDate;
    @XmlElement(name = "BankingCustomerNo")
    protected String bankingCustomerNo;
    @XmlElement(name = "CardType")
    protected String cardType;
    @XmlElement(name = "CardNo")
    protected String cardNo;
    @XmlElement(name = "CardStatCode")
    protected String cardStatCode;
    @XmlElement(name = "CardSubStatCode")
    protected String cardSubStatCode;
    @XmlElement(name = "CardStatDescription")
    protected String cardStatDescription;
    @XmlElement(name = "MainCardNo")
    protected String mainCardNo;
    @XmlElement(name = "EmbossName")
    protected String embossName;
    @XmlElement(name = "EmbossName2")
    protected String embossName2;
    @XmlElement(name = "CardBrand")
    protected String cardBrand;
    @XmlElement(name = "CardProductName")
    protected String cardProductName;
    @XmlElement(name = "CardProductId")
    protected String cardProductId;
    @XmlElement(name = "CardBranch")
    protected String cardBranch;
    @XmlElement(name = "CustomerNo")
    protected String customerNo;
    @XmlElement(name = "CardLevel")
    protected String cardLevel;
    @XmlElement(name = "AccountNo")
    protected String accountNo;
    @XmlElement(name = "BarcodeNo")
    protected String barcodeNo;

    /**
     * Gets the value of the cardDci property.
     * 
     * @return
     *     possible object is
     *     {@link CardDci }
     *     
     */
    public CardDci getCardDci() {
        return cardDci;
    }

    /**
     * Sets the value of the cardDci property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardDci }
     *     
     */
    public void setCardDci(CardDci value) {
        this.cardDci = value;
    }

    /**
     * Gets the value of the isBusiness property.
     * 
     */
    public boolean isIsBusiness() {
        return isBusiness;
    }

    /**
     * Sets the value of the isBusiness property.
     * 
     */
    public void setIsBusiness(boolean value) {
        this.isBusiness = value;
    }

    /**
     * Gets the value of the issuingFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIssuingFee() {
        return issuingFee;
    }

    /**
     * Sets the value of the issuingFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIssuingFee(BigDecimal value) {
        this.issuingFee = value;
    }

    /**
     * Gets the value of the ttlHstBalCurr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTtlHstBalCurr() {
        return ttlHstBalCurr;
    }

    /**
     * Sets the value of the ttlHstBalCurr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTtlHstBalCurr(BigDecimal value) {
        this.ttlHstBalCurr = value;
    }

    /**
     * Gets the value of the ttlCrdBalCurr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTtlCrdBalCurr() {
        return ttlCrdBalCurr;
    }

    /**
     * Sets the value of the ttlCrdBalCurr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTtlCrdBalCurr(BigDecimal value) {
        this.ttlCrdBalCurr = value;
    }

    /**
     * Gets the value of the orderAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * Sets the value of the orderAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOrderAmount(BigDecimal value) {
        this.orderAmount = value;
    }

    /**
     * Gets the value of the chipBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChipBalance() {
        return chipBalance;
    }

    /**
     * Sets the value of the chipBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChipBalance(BigDecimal value) {
        this.chipBalance = value;
    }

    /**
     * Gets the value of the pinRetryCount property.
     * 
     */
    public short getPinRetryCount() {
        return pinRetryCount;
    }

    /**
     * Sets the value of the pinRetryCount property.
     * 
     */
    public void setPinRetryCount(short value) {
        this.pinRetryCount = value;
    }

    /**
     * Gets the value of the offlinePin property.
     * 
     */
    public short getOfflinePin() {
        return offlinePin;
    }

    /**
     * Sets the value of the offlinePin property.
     * 
     */
    public void setOfflinePin(short value) {
        this.offlinePin = value;
    }

    /**
     * Gets the value of the embossDate property.
     * 
     */
    public long getEmbossDate() {
        return embossDate;
    }

    /**
     * Sets the value of the embossDate property.
     * 
     */
    public void setEmbossDate(long value) {
        this.embossDate = value;
    }

    /**
     * Gets the value of the logoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoCode() {
        return logoCode;
    }

    /**
     * Sets the value of the logoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoCode(String value) {
        this.logoCode = value;
    }

    /**
     * Gets the value of the courierStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourierStatus() {
        return courierStatus;
    }

    /**
     * Sets the value of the courierStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourierStatus(String value) {
        this.courierStatus = value;
    }

    /**
     * Gets the value of the lastPinTryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPinTryDate() {
        return lastPinTryDate;
    }

    /**
     * Sets the value of the lastPinTryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPinTryDate(String value) {
        this.lastPinTryDate = value;
    }

    /**
     * Gets the value of the oldCardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldCardNo() {
        return oldCardNo;
    }

    /**
     * Sets the value of the oldCardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldCardNo(String value) {
        this.oldCardNo = value;
    }

    /**
     * Gets the value of the cardStatChangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardStatChangeDate() {
        return cardStatChangeDate;
    }

    /**
     * Sets the value of the cardStatChangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardStatChangeDate(String value) {
        this.cardStatChangeDate = value;
    }

    /**
     * Gets the value of the atc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtc() {
        return atc;
    }

    /**
     * Sets the value of the atc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtc(String value) {
        this.atc = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the remainingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemainingLimit() {
        return remainingLimit;
    }

    /**
     * Sets the value of the remainingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemainingLimit(String value) {
        this.remainingLimit = value;
    }

    /**
     * Gets the value of the cashLimitRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashLimitRatio() {
        return cashLimitRatio;
    }

    /**
     * Sets the value of the cashLimitRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashLimitRatio(String value) {
        this.cashLimitRatio = value;
    }

    /**
     * Gets the value of the cvv2RetryCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvv2RetryCount() {
        return cvv2RetryCount;
    }

    /**
     * Sets the value of the cvv2RetryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvv2RetryCount(String value) {
        this.cvv2RetryCount = value;
    }

    /**
     * Gets the value of the blockedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockedDate() {
        return blockedDate;
    }

    /**
     * Sets the value of the blockedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockedDate(String value) {
        this.blockedDate = value;
    }

    /**
     * Gets the value of the blockedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockedTime() {
        return blockedTime;
    }

    /**
     * Sets the value of the blockedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockedTime(String value) {
        this.blockedTime = value;
    }

    /**
     * Gets the value of the cardUpdateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardUpdateUser() {
        return cardUpdateUser;
    }

    /**
     * Sets the value of the cardUpdateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardUpdateUser(String value) {
        this.cardUpdateUser = value;
    }

    /**
     * Gets the value of the cardCancelReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCancelReason() {
        return cardCancelReason;
    }

    /**
     * Sets the value of the cardCancelReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCancelReason(String value) {
        this.cardCancelReason = value;
    }

    /**
     * Gets the value of the personalizationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalizationDate() {
        return personalizationDate;
    }

    /**
     * Sets the value of the personalizationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalizationDate(String value) {
        this.personalizationDate = value;
    }

    /**
     * Gets the value of the enrollmentNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentNo() {
        return enrollmentNo;
    }

    /**
     * Sets the value of the enrollmentNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentNo(String value) {
        this.enrollmentNo = value;
    }

    /**
     * Gets the value of the financialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialType() {
        return financialType;
    }

    /**
     * Sets the value of the financialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialType(String value) {
        this.financialType = value;
    }

    /**
     * Gets the value of the lastTxnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTxnDate() {
        return lastTxnDate;
    }

    /**
     * Sets the value of the lastTxnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTxnDate(String value) {
        this.lastTxnDate = value;
    }

    /**
     * Gets the value of the lastTxnTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTxnTime() {
        return lastTxnTime;
    }

    /**
     * Sets the value of the lastTxnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTxnTime(String value) {
        this.lastTxnTime = value;
    }

    /**
     * Gets the value of the lastTxnAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTxnAmount() {
        return lastTxnAmount;
    }

    /**
     * Sets the value of the lastTxnAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTxnAmount(String value) {
        this.lastTxnAmount = value;
    }

    /**
     * Gets the value of the firstUsageDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstUsageDate() {
        return firstUsageDate;
    }

    /**
     * Sets the value of the firstUsageDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstUsageDate(String value) {
        this.firstUsageDate = value;
    }

    /**
     * Gets the value of the closeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloseDate() {
        return closeDate;
    }

    /**
     * Sets the value of the closeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseDate(String value) {
        this.closeDate = value;
    }

    /**
     * Gets the value of the renewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewalDate() {
        return renewalDate;
    }

    /**
     * Sets the value of the renewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewalDate(String value) {
        this.renewalDate = value;
    }

    /**
     * Gets the value of the bankingCustomerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankingCustomerNo() {
        return bankingCustomerNo;
    }

    /**
     * Sets the value of the bankingCustomerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankingCustomerNo(String value) {
        this.bankingCustomerNo = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the cardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * Sets the value of the cardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNo(String value) {
        this.cardNo = value;
    }

    /**
     * Gets the value of the cardStatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardStatCode() {
        return cardStatCode;
    }

    /**
     * Sets the value of the cardStatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardStatCode(String value) {
        this.cardStatCode = value;
    }

    /**
     * Gets the value of the cardSubStatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardSubStatCode() {
        return cardSubStatCode;
    }

    /**
     * Sets the value of the cardSubStatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardSubStatCode(String value) {
        this.cardSubStatCode = value;
    }

    /**
     * Gets the value of the cardStatDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardStatDescription() {
        return cardStatDescription;
    }

    /**
     * Sets the value of the cardStatDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardStatDescription(String value) {
        this.cardStatDescription = value;
    }

    /**
     * Gets the value of the mainCardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainCardNo() {
        return mainCardNo;
    }

    /**
     * Sets the value of the mainCardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainCardNo(String value) {
        this.mainCardNo = value;
    }

    /**
     * Gets the value of the embossName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmbossName() {
        return embossName;
    }

    /**
     * Sets the value of the embossName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmbossName(String value) {
        this.embossName = value;
    }

    /**
     * Gets the value of the embossName2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmbossName2() {
        return embossName2;
    }

    /**
     * Sets the value of the embossName2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmbossName2(String value) {
        this.embossName2 = value;
    }

    /**
     * Gets the value of the cardBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBrand() {
        return cardBrand;
    }

    /**
     * Sets the value of the cardBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBrand(String value) {
        this.cardBrand = value;
    }

    /**
     * Gets the value of the cardProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardProductName() {
        return cardProductName;
    }

    /**
     * Sets the value of the cardProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardProductName(String value) {
        this.cardProductName = value;
    }

    /**
     * Gets the value of the cardProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardProductId() {
        return cardProductId;
    }

    /**
     * Sets the value of the cardProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardProductId(String value) {
        this.cardProductId = value;
    }

    /**
     * Gets the value of the cardBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBranch() {
        return cardBranch;
    }

    /**
     * Sets the value of the cardBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBranch(String value) {
        this.cardBranch = value;
    }

    /**
     * Gets the value of the customerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * Sets the value of the customerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNo(String value) {
        this.customerNo = value;
    }

    /**
     * Gets the value of the cardLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardLevel() {
        return cardLevel;
    }

    /**
     * Sets the value of the cardLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardLevel(String value) {
        this.cardLevel = value;
    }

    /**
     * Gets the value of the accountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the barcodeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcodeNo() {
        return barcodeNo;
    }

    /**
     * Sets the value of the barcodeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcodeNo(String value) {
        this.barcodeNo = value;
    }

}
