//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.29 at 09:00:37 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CityTypeResponce complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CityTypeResponce"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{Smartsoft.Integration.Services}ServiceResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CityList" type="{Smartsoft.Integration.Services}ArrayOfCityTypeInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CityTypeResponce", propOrder = {
    "cityList"
})
public class CityTypeResponce
    extends ServiceResponse
{

    @XmlElement(name = "CityList")
    protected ArrayOfCityTypeInfo cityList;

    /**
     * Gets the value of the cityList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCityTypeInfo }
     *     
     */
    public ArrayOfCityTypeInfo getCityList() {
        return cityList;
    }

    /**
     * Sets the value of the cityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCityTypeInfo }
     *     
     */
    public void setCityList(ArrayOfCityTypeInfo value) {
        this.cityList = value;
    }

}
