//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.21 at 09:26:50 PM IST 
//


package com.mycardsolutions.webservice.soapdto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EODControlResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EODControlResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{Smartsoft.Integration.Services}ServiceResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HasEODFinished" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="LastEodDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EODControlResponse", propOrder = {
    "hasEODFinished",
    "lastEodDate"
})
public class EODControlResponse
    extends ServiceResponse
{

    @XmlElement(name = "HasEODFinished")
    protected boolean hasEODFinished;
    @XmlElement(name = "LastEodDate")
    protected String lastEodDate;

    /**
     * Gets the value of the hasEODFinished property.
     * 
     */
    public boolean isHasEODFinished() {
        return hasEODFinished;
    }

    /**
     * Sets the value of the hasEODFinished property.
     * 
     */
    public void setHasEODFinished(boolean value) {
        this.hasEODFinished = value;
    }

    /**
     * Gets the value of the lastEodDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastEodDate() {
        return lastEodDate;
    }

    /**
     * Sets the value of the lastEodDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastEodDate(String value) {
        this.lastEodDate = value;
    }

}
