//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.02 at 10:11:22 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCustomerTypeListResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCustomerTypeListResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{Smartsoft.Integration.Services}ServiceResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustomerTypeInfoList" type="{Smartsoft.Integration.Services}ArrayOfCustomerTypeInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCustomerTypeListResponse", propOrder = {
    "customerTypeInfoList"
})
public class GetCustomerTypeListResponse
    extends ServiceResponse
{

    @XmlElement(name = "CustomerTypeInfoList")
    protected ArrayOfCustomerTypeInfo customerTypeInfoList;

    /**
     * Gets the value of the customerTypeInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCustomerTypeInfo }
     *     
     */
    public ArrayOfCustomerTypeInfo getCustomerTypeInfoList() {
        return customerTypeInfoList;
    }

    /**
     * Sets the value of the customerTypeInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCustomerTypeInfo }
     *     
     */
    public void setCustomerTypeInfoList(ArrayOfCustomerTypeInfo value) {
        this.customerTypeInfoList = value;
    }

}
