//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.02 at 10:11:22 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mycardsolutions.webservice.soapdto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SWSessionInfo_QNAME = new QName("Smartsoft.Integration.Services", "SWSessionInfo");
    private final static QName _CustomerInfoPhoneWorkExtension_QNAME = new QName("Smartsoft.Integration.Services", "PhoneWorkExtension");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mycardsolutions.webservice.soapdto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSLoginUser }
     * 
     */
    public WSLoginUser createWSLoginUser() {
        return new WSLoginUser();
    }

    /**
     * Create an instance of {@link WSLoginUserResponse }
     * 
     */
    public WSLoginUserResponse createWSLoginUserResponse() {
        return new WSLoginUserResponse();
    }

    /**
     * Create an instance of {@link WSLoginResponse }
     * 
     */
    public WSLoginResponse createWSLoginResponse() {
        return new WSLoginResponse();
    }

    /**
     * Create an instance of {@link CloseSessionServiceResponse }
     * 
     */
    public CloseSessionServiceResponse createCloseSessionServiceResponse() {
        return new CloseSessionServiceResponse();
    }

    /**
     * Create an instance of {@link CloseSessionServiceResponseResponse }
     * 
     */
    public CloseSessionServiceResponseResponse createCloseSessionServiceResponseResponse() {
        return new CloseSessionServiceResponseResponse();
    }

    /**
     * Create an instance of {@link ServiceResponse }
     * 
     */
    public ServiceResponse createServiceResponse() {
        return new ServiceResponse();
    }

    /**
     * Create an instance of {@link SWSessionInfo }
     * 
     */
    public SWSessionInfo createSWSessionInfo() {
        return new SWSessionInfo();
    }

    /**
     * Create an instance of {@link CardRenewalProcess }
     * 
     */
    public CardRenewalProcess createCardRenewalProcess() {
        return new CardRenewalProcess();
    }

    /**
     * Create an instance of {@link CardRenewalProcessResponse }
     * 
     */
    public CardRenewalProcessResponse createCardRenewalProcessResponse() {
        return new CardRenewalProcessResponse();
    }

    /**
     * Create an instance of {@link CardRenewalResponse }
     * 
     */
    public CardRenewalResponse createCardRenewalResponse() {
        return new CardRenewalResponse();
    }

    /**
     * Create an instance of {@link ControlEOD }
     * 
     */
    public ControlEOD createControlEOD() {
        return new ControlEOD();
    }

    /**
     * Create an instance of {@link ControlEODResponse }
     * 
     */
    public ControlEODResponse createControlEODResponse() {
        return new ControlEODResponse();
    }

    /**
     * Create an instance of {@link EODControlResponse }
     * 
     */
    public EODControlResponse createEODControlResponse() {
        return new EODControlResponse();
    }

    /**
     * Create an instance of {@link CreateCustomer }
     * 
     */
    public CreateCustomer createCreateCustomer() {
        return new CreateCustomer();
    }

    /**
     * Create an instance of {@link CustomerInfo }
     * 
     */
    public CustomerInfo createCustomerInfo() {
        return new CustomerInfo();
    }

    /**
     * Create an instance of {@link CreateCustomerResponse }
     * 
     */
    public CreateCustomerResponse createCreateCustomerResponse() {
        return new CreateCustomerResponse();
    }

    /**
     * Create an instance of {@link CustomerCreateResponse }
     * 
     */
    public CustomerCreateResponse createCustomerCreateResponse() {
        return new CustomerCreateResponse();
    }

    /**
     * Create an instance of {@link CreateCard }
     * 
     */
    public CreateCard createCreateCard() {
        return new CreateCard();
    }

    /**
     * Create an instance of {@link CardRequest }
     * 
     */
    public CardRequest createCardRequest() {
        return new CardRequest();
    }

    /**
     * Create an instance of {@link CreateCardResponse }
     * 
     */
    public CreateCardResponse createCreateCardResponse() {
        return new CreateCardResponse();
    }

    /**
     * Create an instance of {@link CardGenerateResponse }
     * 
     */
    public CardGenerateResponse createCardGenerateResponse() {
        return new CardGenerateResponse();
    }

    /**
     * Create an instance of {@link Cvv2Check }
     * 
     */
    public Cvv2Check createCvv2Check() {
        return new Cvv2Check();
    }

    /**
     * Create an instance of {@link Cvv2CheckResponse }
     * 
     */
    public Cvv2CheckResponse createCvv2CheckResponse() {
        return new Cvv2CheckResponse();
    }

    /**
     * Create an instance of {@link CvvUnblockResponse }
     * 
     */
    public CvvUnblockResponse createCvvUnblockResponse() {
        return new CvvUnblockResponse();
    }

    /**
     * Create an instance of {@link CvvUnblockResponseResponse }
     * 
     */
    public CvvUnblockResponseResponse createCvvUnblockResponseResponse() {
        return new CvvUnblockResponseResponse();
    }

    /**
     * Create an instance of {@link Cvv2UnblockResponse }
     * 
     */
    public Cvv2UnblockResponse createCvv2UnblockResponse() {
        return new Cvv2UnblockResponse();
    }

    /**
     * Create an instance of {@link GetCardAllTransactions }
     * 
     */
    public GetCardAllTransactions createGetCardAllTransactions() {
        return new GetCardAllTransactions();
    }

    /**
     * Create an instance of {@link Paging }
     * 
     */
    public Paging createPaging() {
        return new Paging();
    }

    /**
     * Create an instance of {@link GetCardAllTransactionsResponse }
     * 
     */
    public GetCardAllTransactionsResponse createGetCardAllTransactionsResponse() {
        return new GetCardAllTransactionsResponse();
    }

    /**
     * Create an instance of {@link CardAllTransectionsResponse }
     * 
     */
    public CardAllTransectionsResponse createCardAllTransectionsResponse() {
        return new CardAllTransectionsResponse();
    }

    /**
     * Create an instance of {@link GetTxnById }
     * 
     */
    public GetTxnById createGetTxnById() {
        return new GetTxnById();
    }

    /**
     * Create an instance of {@link GetTxnByIdResponse }
     * 
     */
    public GetTxnByIdResponse createGetTxnByIdResponse() {
        return new GetTxnByIdResponse();
    }

    /**
     * Create an instance of {@link SWGetCardInfoResponse }
     * 
     */
    public SWGetCardInfoResponse createSWGetCardInfoResponse() {
        return new SWGetCardInfoResponse();
    }

    /**
     * Create an instance of {@link SWGetCardInfoResponseResponse }
     * 
     */
    public SWGetCardInfoResponseResponse createSWGetCardInfoResponseResponse() {
        return new SWGetCardInfoResponseResponse();
    }

    /**
     * Create an instance of {@link GetCardInfoResponse }
     * 
     */
    public GetCardInfoResponse createGetCardInfoResponse() {
        return new GetCardInfoResponse();
    }

    /**
     * Create an instance of {@link GetVirtualCardInfoRsp }
     * 
     */
    public GetVirtualCardInfoRsp createGetVirtualCardInfoRsp() {
        return new GetVirtualCardInfoRsp();
    }

    /**
     * Create an instance of {@link GetVirtualCardInfoRspResponse }
     * 
     */
    public GetVirtualCardInfoRspResponse createGetVirtualCardInfoRspResponse() {
        return new GetVirtualCardInfoRspResponse();
    }

    /**
     * Create an instance of {@link GetVirtualCardInfoResponse }
     * 
     */
    public GetVirtualCardInfoResponse createGetVirtualCardInfoResponse() {
        return new GetVirtualCardInfoResponse();
    }

    /**
     * Create an instance of {@link CreateCardTransactionResp }
     * 
     */
    public CreateCardTransactionResp createCreateCardTransactionResp() {
        return new CreateCardTransactionResp();
    }

    /**
     * Create an instance of {@link CreateCardTransactionRespResponse }
     * 
     */
    public CreateCardTransactionRespResponse createCreateCardTransactionRespResponse() {
        return new CreateCardTransactionRespResponse();
    }

    /**
     * Create an instance of {@link CreateCardTransactionResponse }
     * 
     */
    public CreateCardTransactionResponse createCreateCardTransactionResponse() {
        return new CreateCardTransactionResponse();
    }

    /**
     * Create an instance of {@link ReverseCardTransactionResp }
     * 
     */
    public ReverseCardTransactionResp createReverseCardTransactionResp() {
        return new ReverseCardTransactionResp();
    }

    /**
     * Create an instance of {@link ReverseCardTransactionRespResponse }
     * 
     */
    public ReverseCardTransactionRespResponse createReverseCardTransactionRespResponse() {
        return new ReverseCardTransactionRespResponse();
    }

    /**
     * Create an instance of {@link GetCustomerCardInfo }
     * 
     */
    public GetCustomerCardInfo createGetCustomerCardInfo() {
        return new GetCustomerCardInfo();
    }

    /**
     * Create an instance of {@link GetCustomerCardInfoResponse }
     * 
     */
    public GetCustomerCardInfoResponse createGetCustomerCardInfoResponse() {
        return new GetCustomerCardInfoResponse();
    }

    /**
     * Create an instance of {@link GetCustomerCardsResponse }
     * 
     */
    public GetCustomerCardsResponse createGetCustomerCardsResponse() {
        return new GetCustomerCardsResponse();
    }

    /**
     * Create an instance of {@link GetCardStatus }
     * 
     */
    public GetCardStatus createGetCardStatus() {
        return new GetCardStatus();
    }

    /**
     * Create an instance of {@link GetCardStatusResponse }
     * 
     */
    public GetCardStatusResponse createGetCardStatusResponse() {
        return new GetCardStatusResponse();
    }

    /**
     * Create an instance of {@link GetCardStatusListResponse }
     * 
     */
    public GetCardStatusListResponse createGetCardStatusListResponse() {
        return new GetCardStatusListResponse();
    }

    /**
     * Create an instance of {@link GetCustomerGroups }
     * 
     */
    public GetCustomerGroups createGetCustomerGroups() {
        return new GetCustomerGroups();
    }

    /**
     * Create an instance of {@link GetCustomerGroupsResponse }
     * 
     */
    public GetCustomerGroupsResponse createGetCustomerGroupsResponse() {
        return new GetCustomerGroupsResponse();
    }

    /**
     * Create an instance of {@link GetCustomerGroupListResponse }
     * 
     */
    public GetCustomerGroupListResponse createGetCustomerGroupListResponse() {
        return new GetCustomerGroupListResponse();
    }

    /**
     * Create an instance of {@link GetCustomerTypes }
     * 
     */
    public GetCustomerTypes createGetCustomerTypes() {
        return new GetCustomerTypes();
    }

    /**
     * Create an instance of {@link GetCustomerTypesResponse }
     * 
     */
    public GetCustomerTypesResponse createGetCustomerTypesResponse() {
        return new GetCustomerTypesResponse();
    }

    /**
     * Create an instance of {@link GetCustomerTypeListResponse }
     * 
     */
    public GetCustomerTypeListResponse createGetCustomerTypeListResponse() {
        return new GetCustomerTypeListResponse();
    }

    /**
     * Create an instance of {@link GetCityList }
     * 
     */
    public GetCityList createGetCityList() {
        return new GetCityList();
    }

    /**
     * Create an instance of {@link GetCityListResponse }
     * 
     */
    public GetCityListResponse createGetCityListResponse() {
        return new GetCityListResponse();
    }

    /**
     * Create an instance of {@link CityTypeResponce }
     * 
     */
    public CityTypeResponce createCityTypeResponce() {
        return new CityTypeResponce();
    }

    /**
     * Create an instance of {@link GetStateList }
     * 
     */
    public GetStateList createGetStateList() {
        return new GetStateList();
    }

    /**
     * Create an instance of {@link GetStateListResponse }
     * 
     */
    public GetStateListResponse createGetStateListResponse() {
        return new GetStateListResponse();
    }

    /**
     * Create an instance of {@link StateTypeResponce }
     * 
     */
    public StateTypeResponce createStateTypeResponce() {
        return new StateTypeResponce();
    }

    /**
     * Create an instance of {@link GetEmbossRequest }
     * 
     */
    public GetEmbossRequest createGetEmbossRequest() {
        return new GetEmbossRequest();
    }

    /**
     * Create an instance of {@link GetEmbossRequestResponse }
     * 
     */
    public GetEmbossRequestResponse createGetEmbossRequestResponse() {
        return new GetEmbossRequestResponse();
    }

    /**
     * Create an instance of {@link CardEmbossRequest }
     * 
     */
    public CardEmbossRequest createCardEmbossRequest() {
        return new CardEmbossRequest();
    }

    /**
     * Create an instance of {@link GetFinancialTypes }
     * 
     */
    public GetFinancialTypes createGetFinancialTypes() {
        return new GetFinancialTypes();
    }

    /**
     * Create an instance of {@link GetFinancialTypesResponse }
     * 
     */
    public GetFinancialTypesResponse createGetFinancialTypesResponse() {
        return new GetFinancialTypesResponse();
    }

    /**
     * Create an instance of {@link GetFinancialTypeListResponse }
     * 
     */
    public GetFinancialTypeListResponse createGetFinancialTypeListResponse() {
        return new GetFinancialTypeListResponse();
    }

    /**
     * Create an instance of {@link GetLogoCodes }
     * 
     */
    public GetLogoCodes createGetLogoCodes() {
        return new GetLogoCodes();
    }

    /**
     * Create an instance of {@link GetLogoCodesResponse }
     * 
     */
    public GetLogoCodesResponse createGetLogoCodesResponse() {
        return new GetLogoCodesResponse();
    }

    /**
     * Create an instance of {@link GetLogoCodeListResponse }
     * 
     */
    public GetLogoCodeListResponse createGetLogoCodeListResponse() {
        return new GetLogoCodeListResponse();
    }

    /**
     * Create an instance of {@link GetMainAccount }
     * 
     */
    public GetMainAccount createGetMainAccount() {
        return new GetMainAccount();
    }

    /**
     * Create an instance of {@link GetMainAccountResponse }
     * 
     */
    public GetMainAccountResponse createGetMainAccountResponse() {
        return new GetMainAccountResponse();
    }

    /**
     * Create an instance of {@link MainAccount }
     * 
     */
    public MainAccount createMainAccount() {
        return new MainAccount();
    }

    /**
     * Create an instance of {@link GetProducts }
     * 
     */
    public GetProducts createGetProducts() {
        return new GetProducts();
    }

    /**
     * Create an instance of {@link GetProductsResponse }
     * 
     */
    public GetProductsResponse createGetProductsResponse() {
        return new GetProductsResponse();
    }

    /**
     * Create an instance of {@link GetProductListResponse }
     * 
     */
    public GetProductListResponse createGetProductListResponse() {
        return new GetProductListResponse();
    }

    /**
     * Create an instance of {@link GetBranchList }
     * 
     */
    public GetBranchList createGetBranchList() {
        return new GetBranchList();
    }

    /**
     * Create an instance of {@link GetBranchListResponse }
     * 
     */
    public GetBranchListResponse createGetBranchListResponse() {
        return new GetBranchListResponse();
    }

    /**
     * Create an instance of {@link BranchListResponse }
     * 
     */
    public BranchListResponse createBranchListResponse() {
        return new BranchListResponse();
    }

    /**
     * Create an instance of {@link GetTxnDefProcess }
     * 
     */
    public GetTxnDefProcess createGetTxnDefProcess() {
        return new GetTxnDefProcess();
    }

    /**
     * Create an instance of {@link GetTxnDefProcessResponse }
     * 
     */
    public GetTxnDefProcessResponse createGetTxnDefProcessResponse() {
        return new GetTxnDefProcessResponse();
    }

    /**
     * Create an instance of {@link GetTxnDefResponse }
     * 
     */
    public GetTxnDefResponse createGetTxnDefResponse() {
        return new GetTxnDefResponse();
    }

    /**
     * Create an instance of {@link MatchCardAndCustomer }
     * 
     */
    public MatchCardAndCustomer createMatchCardAndCustomer() {
        return new MatchCardAndCustomer();
    }

    /**
     * Create an instance of {@link MatchCardAndCustomerResponse }
     * 
     */
    public MatchCardAndCustomerResponse createMatchCardAndCustomerResponse() {
        return new MatchCardAndCustomerResponse();
    }

    /**
     * Create an instance of {@link MatchCardAndNewCustomer }
     * 
     */
    public MatchCardAndNewCustomer createMatchCardAndNewCustomer() {
        return new MatchCardAndNewCustomer();
    }

    /**
     * Create an instance of {@link MatchCardAndNewCustomerResponse }
     * 
     */
    public MatchCardAndNewCustomerResponse createMatchCardAndNewCustomerResponse() {
        return new MatchCardAndNewCustomerResponse();
    }

    /**
     * Create an instance of {@link PinSet }
     * 
     */
    public PinSet createPinSet() {
        return new PinSet();
    }

    /**
     * Create an instance of {@link PinSetResponse }
     * 
     */
    public PinSetResponse createPinSetResponse() {
        return new PinSetResponse();
    }

    /**
     * Create an instance of {@link PinChange }
     * 
     */
    public PinChange createPinChange() {
        return new PinChange();
    }

    /**
     * Create an instance of {@link PinChangeResponse }
     * 
     */
    public PinChangeResponse createPinChangeResponse() {
        return new PinChangeResponse();
    }

    /**
     * Create an instance of {@link PinCheck }
     * 
     */
    public PinCheck createPinCheck() {
        return new PinCheck();
    }

    /**
     * Create an instance of {@link PinCheckResponse }
     * 
     */
    public PinCheckResponse createPinCheckResponse() {
        return new PinCheckResponse();
    }

    /**
     * Create an instance of {@link PinSetClear }
     * 
     */
    public PinSetClear createPinSetClear() {
        return new PinSetClear();
    }

    /**
     * Create an instance of {@link PinSetClearResponse }
     * 
     */
    public PinSetClearResponse createPinSetClearResponse() {
        return new PinSetClearResponse();
    }

    /**
     * Create an instance of {@link PinChangeClear }
     * 
     */
    public PinChangeClear createPinChangeClear() {
        return new PinChangeClear();
    }

    /**
     * Create an instance of {@link PinChangeClearResponse }
     * 
     */
    public PinChangeClearResponse createPinChangeClearResponse() {
        return new PinChangeClearResponse();
    }

    /**
     * Create an instance of {@link PinCheckClear }
     * 
     */
    public PinCheckClear createPinCheckClear() {
        return new PinCheckClear();
    }

    /**
     * Create an instance of {@link PinCheckClearResponse }
     * 
     */
    public PinCheckClearResponse createPinCheckClearResponse() {
        return new PinCheckClearResponse();
    }

    /**
     * Create an instance of {@link PinBlock }
     * 
     */
    public PinBlock createPinBlock() {
        return new PinBlock();
    }

    /**
     * Create an instance of {@link PinBlockResponse }
     * 
     */
    public PinBlockResponse createPinBlockResponse() {
        return new PinBlockResponse();
    }

    /**
     * Create an instance of {@link GetCardVerificationDataRsp }
     * 
     */
    public GetCardVerificationDataRsp createGetCardVerificationDataRsp() {
        return new GetCardVerificationDataRsp();
    }

    /**
     * Create an instance of {@link GetCardVerificationDataRspResponse }
     * 
     */
    public GetCardVerificationDataRspResponse createGetCardVerificationDataRspResponse() {
        return new GetCardVerificationDataRspResponse();
    }

    /**
     * Create an instance of {@link GetCardVerificationDataResponse }
     * 
     */
    public GetCardVerificationDataResponse createGetCardVerificationDataResponse() {
        return new GetCardVerificationDataResponse();
    }

    /**
     * Create an instance of {@link RestrictCardTxn }
     * 
     */
    public RestrictCardTxn createRestrictCardTxn() {
        return new RestrictCardTxn();
    }

    /**
     * Create an instance of {@link RestrictCardTxnResponse }
     * 
     */
    public RestrictCardTxnResponse createRestrictCardTxnResponse() {
        return new RestrictCardTxnResponse();
    }

    /**
     * Create an instance of {@link CardStatControlRsp }
     * 
     */
    public CardStatControlRsp createCardStatControlRsp() {
        return new CardStatControlRsp();
    }

    /**
     * Create an instance of {@link CardStatControlRspResponse }
     * 
     */
    public CardStatControlRspResponse createCardStatControlRspResponse() {
        return new CardStatControlRspResponse();
    }

    /**
     * Create an instance of {@link CardStatControlResponse }
     * 
     */
    public CardStatControlResponse createCardStatControlResponse() {
        return new CardStatControlResponse();
    }

    /**
     * Create an instance of {@link UpdateCardStatus }
     * 
     */
    public UpdateCardStatus createUpdateCardStatus() {
        return new UpdateCardStatus();
    }

    /**
     * Create an instance of {@link UpdateCardStatusResponse }
     * 
     */
    public UpdateCardStatusResponse createUpdateCardStatusResponse() {
        return new UpdateCardStatusResponse();
    }

    /**
     * Create an instance of {@link UpdateCustomer }
     * 
     */
    public UpdateCustomer createUpdateCustomer() {
        return new UpdateCustomer();
    }

    /**
     * Create an instance of {@link UpdateCustomerResponse }
     * 
     */
    public UpdateCustomerResponse createUpdateCustomerResponse() {
        return new UpdateCustomerResponse();
    }

    /**
     * Create an instance of {@link GetCustomer }
     * 
     */
    public GetCustomer createGetCustomer() {
        return new GetCustomer();
    }

    /**
     * Create an instance of {@link GetCustomerResponse }
     * 
     */
    public GetCustomerResponse createGetCustomerResponse() {
        return new GetCustomerResponse();
    }

    /**
     * Create an instance of {@link GetCustomerInfoResponse }
     * 
     */
    public GetCustomerInfoResponse createGetCustomerInfoResponse() {
        return new GetCustomerInfoResponse();
    }

    /**
     * Create an instance of {@link UpdateMobileNoAndBankingCustomerNo }
     * 
     */
    public UpdateMobileNoAndBankingCustomerNo createUpdateMobileNoAndBankingCustomerNo() {
        return new UpdateMobileNoAndBankingCustomerNo();
    }

    /**
     * Create an instance of {@link UpdateMobileNoAndBankingCustomerNoResponse }
     * 
     */
    public UpdateMobileNoAndBankingCustomerNoResponse createUpdateMobileNoAndBankingCustomerNoResponse() {
        return new UpdateMobileNoAndBankingCustomerNoResponse();
    }

    /**
     * Create an instance of {@link GetCardRestrictionInfo }
     * 
     */
    public GetCardRestrictionInfo createGetCardRestrictionInfo() {
        return new GetCardRestrictionInfo();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link GetCardRestrictionInfoResponse }
     * 
     */
    public GetCardRestrictionInfoResponse createGetCardRestrictionInfoResponse() {
        return new GetCardRestrictionInfoResponse();
    }

    /**
     * Create an instance of {@link GetCardRestrictionInfoResponse2 }
     * 
     */
    public GetCardRestrictionInfoResponse2 createGetCardRestrictionInfoResponse2() {
        return new GetCardRestrictionInfoResponse2();
    }

    /**
     * Create an instance of {@link GetCardTxnFeeProfileInfo }
     * 
     */
    public GetCardTxnFeeProfileInfo createGetCardTxnFeeProfileInfo() {
        return new GetCardTxnFeeProfileInfo();
    }

    /**
     * Create an instance of {@link GetCardTxnFeeProfileInfoResponse }
     * 
     */
    public GetCardTxnFeeProfileInfoResponse createGetCardTxnFeeProfileInfoResponse() {
        return new GetCardTxnFeeProfileInfoResponse();
    }

    /**
     * Create an instance of {@link CardTxnFeeProfileInfoResponse }
     * 
     */
    public CardTxnFeeProfileInfoResponse createCardTxnFeeProfileInfoResponse() {
        return new CardTxnFeeProfileInfoResponse();
    }

    /**
     * Create an instance of {@link CardRestriction }
     * 
     */
    public CardRestriction createCardRestriction() {
        return new CardRestriction();
    }

    /**
     * Create an instance of {@link CardRestrictionResponse }
     * 
     */
    public CardRestrictionResponse createCardRestrictionResponse() {
        return new CardRestrictionResponse();
    }

    /**
     * Create an instance of {@link MultiTopupToPrepaid }
     * 
     */
    public MultiTopupToPrepaid createMultiTopupToPrepaid() {
        return new MultiTopupToPrepaid();
    }

    /**
     * Create an instance of {@link ArrayOfTopupToPrepaidObj }
     * 
     */
    public ArrayOfTopupToPrepaidObj createArrayOfTopupToPrepaidObj() {
        return new ArrayOfTopupToPrepaidObj();
    }

    /**
     * Create an instance of {@link MultiTopupToPrepaidResponse }
     * 
     */
    public MultiTopupToPrepaidResponse createMultiTopupToPrepaidResponse() {
        return new MultiTopupToPrepaidResponse();
    }

    /**
     * Create an instance of {@link ArrayOfCardPaymentResponse }
     * 
     */
    public ArrayOfCardPaymentResponse createArrayOfCardPaymentResponse() {
        return new ArrayOfCardPaymentResponse();
    }

    /**
     * Create an instance of {@link ProductRestriction }
     * 
     */
    public ProductRestriction createProductRestriction() {
        return new ProductRestriction();
    }

    /**
     * Create an instance of {@link ProductRestrictionResponse }
     * 
     */
    public ProductRestrictionResponse createProductRestrictionResponse() {
        return new ProductRestrictionResponse();
    }

    /**
     * Create an instance of {@link TopupToPrepaid }
     * 
     */
    public TopupToPrepaid createTopupToPrepaid() {
        return new TopupToPrepaid();
    }

    /**
     * Create an instance of {@link TopupToPrepaidObj }
     * 
     */
    public TopupToPrepaidObj createTopupToPrepaidObj() {
        return new TopupToPrepaidObj();
    }

    /**
     * Create an instance of {@link TopupToPrepaidResponse }
     * 
     */
    public TopupToPrepaidResponse createTopupToPrepaidResponse() {
        return new TopupToPrepaidResponse();
    }

    /**
     * Create an instance of {@link CardPaymentResponse }
     * 
     */
    public CardPaymentResponse createCardPaymentResponse() {
        return new CardPaymentResponse();
    }

    /**
     * Create an instance of {@link TopupToPrepaidReversal }
     * 
     */
    public TopupToPrepaidReversal createTopupToPrepaidReversal() {
        return new TopupToPrepaidReversal();
    }

    /**
     * Create an instance of {@link TopupToPrepaidReversalResponse }
     * 
     */
    public TopupToPrepaidReversalResponse createTopupToPrepaidReversalResponse() {
        return new TopupToPrepaidReversalResponse();
    }

    /**
     * Create an instance of {@link DirectiveDefinitionAndUpdate }
     * 
     */
    public DirectiveDefinitionAndUpdate createDirectiveDefinitionAndUpdate() {
        return new DirectiveDefinitionAndUpdate();
    }

    /**
     * Create an instance of {@link DirectiveDefinitionAndUpdateResponse }
     * 
     */
    public DirectiveDefinitionAndUpdateResponse createDirectiveDefinitionAndUpdateResponse() {
        return new DirectiveDefinitionAndUpdateResponse();
    }

    /**
     * Create an instance of {@link CardVerificationResp }
     * 
     */
    public CardVerificationResp createCardVerificationResp() {
        return new CardVerificationResp();
    }

    /**
     * Create an instance of {@link CardVerificationRespResponse }
     * 
     */
    public CardVerificationRespResponse createCardVerificationRespResponse() {
        return new CardVerificationRespResponse();
    }

    /**
     * Create an instance of {@link CardVerificationResponse }
     * 
     */
    public CardVerificationResponse createCardVerificationResponse() {
        return new CardVerificationResponse();
    }

    /**
     * Create an instance of {@link BalanceTransferOnlyHost }
     * 
     */
    public BalanceTransferOnlyHost createBalanceTransferOnlyHost() {
        return new BalanceTransferOnlyHost();
    }

    /**
     * Create an instance of {@link BalanceTransferOnlyHostResponse }
     * 
     */
    public BalanceTransferOnlyHostResponse createBalanceTransferOnlyHostResponse() {
        return new BalanceTransferOnlyHostResponse();
    }

    /**
     * Create an instance of {@link TotalBalanceTransferHostAndChip }
     * 
     */
    public TotalBalanceTransferHostAndChip createTotalBalanceTransferHostAndChip() {
        return new TotalBalanceTransferHostAndChip();
    }

    /**
     * Create an instance of {@link TotalBalanceTransferHostAndChipResponse }
     * 
     */
    public TotalBalanceTransferHostAndChipResponse createTotalBalanceTransferHostAndChipResponse() {
        return new TotalBalanceTransferHostAndChipResponse();
    }

    /**
     * Create an instance of {@link TransactionFeeCalculation }
     * 
     */
    public TransactionFeeCalculation createTransactionFeeCalculation() {
        return new TransactionFeeCalculation();
    }

    /**
     * Create an instance of {@link TransactionFeeCalculationResponse }
     * 
     */
    public TransactionFeeCalculationResponse createTransactionFeeCalculationResponse() {
        return new TransactionFeeCalculationResponse();
    }

    /**
     * Create an instance of {@link CustomerBalanceTransferOnlyHost }
     * 
     */
    public CustomerBalanceTransferOnlyHost createCustomerBalanceTransferOnlyHost() {
        return new CustomerBalanceTransferOnlyHost();
    }

    /**
     * Create an instance of {@link CustomerBalanceTransferOnlyHostResponse }
     * 
     */
    public CustomerBalanceTransferOnlyHostResponse createCustomerBalanceTransferOnlyHostResponse() {
        return new CustomerBalanceTransferOnlyHostResponse();
    }

    /**
     * Create an instance of {@link GetCardAllLimitAndBalanceInfo }
     * 
     */
    public GetCardAllLimitAndBalanceInfo createGetCardAllLimitAndBalanceInfo() {
        return new GetCardAllLimitAndBalanceInfo();
    }

    /**
     * Create an instance of {@link GetCardAllLimitAndBalanceInfoResponse }
     * 
     */
    public GetCardAllLimitAndBalanceInfoResponse createGetCardAllLimitAndBalanceInfoResponse() {
        return new GetCardAllLimitAndBalanceInfoResponse();
    }

    /**
     * Create an instance of {@link CardLimits }
     * 
     */
    public CardLimits createCardLimits() {
        return new CardLimits();
    }

    /**
     * Create an instance of {@link CardLimitsUpdate }
     * 
     */
    public CardLimitsUpdate createCardLimitsUpdate() {
        return new CardLimitsUpdate();
    }

    /**
     * Create an instance of {@link ArrayOfCardLevelLimitsRequest }
     * 
     */
    public ArrayOfCardLevelLimitsRequest createArrayOfCardLevelLimitsRequest() {
        return new ArrayOfCardLevelLimitsRequest();
    }

    /**
     * Create an instance of {@link CardLimitsUpdateResponse }
     * 
     */
    public CardLimitsUpdateResponse createCardLimitsUpdateResponse() {
        return new CardLimitsUpdateResponse();
    }

    /**
     * Create an instance of {@link CompanyInsert }
     * 
     */
    public CompanyInsert createCompanyInsert() {
        return new CompanyInsert();
    }

    /**
     * Create an instance of {@link CstCompany }
     * 
     */
    public CstCompany createCstCompany() {
        return new CstCompany();
    }

    /**
     * Create an instance of {@link ArrayOfCstCompanyAddress }
     * 
     */
    public ArrayOfCstCompanyAddress createArrayOfCstCompanyAddress() {
        return new ArrayOfCstCompanyAddress();
    }

    /**
     * Create an instance of {@link CompanyInsertResponse }
     * 
     */
    public CompanyInsertResponse createCompanyInsertResponse() {
        return new CompanyInsertResponse();
    }

    /**
     * Create an instance of {@link CompanyUpdate }
     * 
     */
    public CompanyUpdate createCompanyUpdate() {
        return new CompanyUpdate();
    }

    /**
     * Create an instance of {@link CompanyUpdateResponse }
     * 
     */
    public CompanyUpdateResponse createCompanyUpdateResponse() {
        return new CompanyUpdateResponse();
    }

    /**
     * Create an instance of {@link SetCardAccountValues }
     * 
     */
    public SetCardAccountValues createSetCardAccountValues() {
        return new SetCardAccountValues();
    }

    /**
     * Create an instance of {@link UpdateCardValuesRequest }
     * 
     */
    public UpdateCardValuesRequest createUpdateCardValuesRequest() {
        return new UpdateCardValuesRequest();
    }

    /**
     * Create an instance of {@link SetCardAccountValuesResponse }
     * 
     */
    public SetCardAccountValuesResponse createSetCardAccountValuesResponse() {
        return new SetCardAccountValuesResponse();
    }

    /**
     * Create an instance of {@link TxnTransferToBankAccount }
     * 
     */
    public TxnTransferToBankAccount createTxnTransferToBankAccount() {
        return new TxnTransferToBankAccount();
    }

    /**
     * Create an instance of {@link TxnTransferToBankAccountResponse }
     * 
     */
    public TxnTransferToBankAccountResponse createTxnTransferToBankAccountResponse() {
        return new TxnTransferToBankAccountResponse();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

    /**
     * Create an instance of {@link ArrayOfLong }
     * 
     */
    public ArrayOfLong createArrayOfLong() {
        return new ArrayOfLong();
    }

    /**
     * Create an instance of {@link ArrayOfAdressInfo }
     * 
     */
    public ArrayOfAdressInfo createArrayOfAdressInfo() {
        return new ArrayOfAdressInfo();
    }

    /**
     * Create an instance of {@link AdressInfo }
     * 
     */
    public AdressInfo createAdressInfo() {
        return new AdressInfo();
    }

    /**
     * Create an instance of {@link ArrayOfCardTxnInfo }
     * 
     */
    public ArrayOfCardTxnInfo createArrayOfCardTxnInfo() {
        return new ArrayOfCardTxnInfo();
    }

    /**
     * Create an instance of {@link CardTxnInfo }
     * 
     */
    public CardTxnInfo createCardTxnInfo() {
        return new CardTxnInfo();
    }

    /**
     * Create an instance of {@link ArrayOfCardDetailInfo }
     * 
     */
    public ArrayOfCardDetailInfo createArrayOfCardDetailInfo() {
        return new ArrayOfCardDetailInfo();
    }

    /**
     * Create an instance of {@link CardDetailInfo }
     * 
     */
    public CardDetailInfo createCardDetailInfo() {
        return new CardDetailInfo();
    }

    /**
     * Create an instance of {@link CardPointInfo }
     * 
     */
    public CardPointInfo createCardPointInfo() {
        return new CardPointInfo();
    }

    /**
     * Create an instance of {@link ArrayOfCustomerCardList }
     * 
     */
    public ArrayOfCustomerCardList createArrayOfCustomerCardList() {
        return new ArrayOfCustomerCardList();
    }

    /**
     * Create an instance of {@link CustomerCardList }
     * 
     */
    public CustomerCardList createCustomerCardList() {
        return new CustomerCardList();
    }

    /**
     * Create an instance of {@link ArrayOfCardStatus }
     * 
     */
    public ArrayOfCardStatus createArrayOfCardStatus() {
        return new ArrayOfCardStatus();
    }

    /**
     * Create an instance of {@link CardStatus }
     * 
     */
    public CardStatus createCardStatus() {
        return new CardStatus();
    }

    /**
     * Create an instance of {@link ArrayOfReasonCode }
     * 
     */
    public ArrayOfReasonCode createArrayOfReasonCode() {
        return new ArrayOfReasonCode();
    }

    /**
     * Create an instance of {@link ReasonCode }
     * 
     */
    public ReasonCode createReasonCode() {
        return new ReasonCode();
    }

    /**
     * Create an instance of {@link ArrayOfCustomerGroupInfo }
     * 
     */
    public ArrayOfCustomerGroupInfo createArrayOfCustomerGroupInfo() {
        return new ArrayOfCustomerGroupInfo();
    }

    /**
     * Create an instance of {@link CustomerGroupInfo }
     * 
     */
    public CustomerGroupInfo createCustomerGroupInfo() {
        return new CustomerGroupInfo();
    }

    /**
     * Create an instance of {@link ArrayOfCustomerTypeInfo }
     * 
     */
    public ArrayOfCustomerTypeInfo createArrayOfCustomerTypeInfo() {
        return new ArrayOfCustomerTypeInfo();
    }

    /**
     * Create an instance of {@link CustomerTypeInfo }
     * 
     */
    public CustomerTypeInfo createCustomerTypeInfo() {
        return new CustomerTypeInfo();
    }

    /**
     * Create an instance of {@link ArrayOfCityTypeInfo }
     * 
     */
    public ArrayOfCityTypeInfo createArrayOfCityTypeInfo() {
        return new ArrayOfCityTypeInfo();
    }

    /**
     * Create an instance of {@link CityTypeInfo }
     * 
     */
    public CityTypeInfo createCityTypeInfo() {
        return new CityTypeInfo();
    }

    /**
     * Create an instance of {@link ArrayOfStateTypeInfo }
     * 
     */
    public ArrayOfStateTypeInfo createArrayOfStateTypeInfo() {
        return new ArrayOfStateTypeInfo();
    }

    /**
     * Create an instance of {@link StateTypeInfo }
     * 
     */
    public StateTypeInfo createStateTypeInfo() {
        return new StateTypeInfo();
    }

    /**
     * Create an instance of {@link ArrayOfFinancialType }
     * 
     */
    public ArrayOfFinancialType createArrayOfFinancialType() {
        return new ArrayOfFinancialType();
    }

    /**
     * Create an instance of {@link FinancialType }
     * 
     */
    public FinancialType createFinancialType() {
        return new FinancialType();
    }

    /**
     * Create an instance of {@link ArrayOfLogoCode }
     * 
     */
    public ArrayOfLogoCode createArrayOfLogoCode() {
        return new ArrayOfLogoCode();
    }

    /**
     * Create an instance of {@link LogoCode }
     * 
     */
    public LogoCode createLogoCode() {
        return new LogoCode();
    }

    /**
     * Create an instance of {@link ArrayOfProductInfo }
     * 
     */
    public ArrayOfProductInfo createArrayOfProductInfo() {
        return new ArrayOfProductInfo();
    }

    /**
     * Create an instance of {@link ProductInfo }
     * 
     */
    public ProductInfo createProductInfo() {
        return new ProductInfo();
    }

    /**
     * Create an instance of {@link ArrayOfBranchList }
     * 
     */
    public ArrayOfBranchList createArrayOfBranchList() {
        return new ArrayOfBranchList();
    }

    /**
     * Create an instance of {@link BranchList }
     * 
     */
    public BranchList createBranchList() {
        return new BranchList();
    }

    /**
     * Create an instance of {@link ArrayOfTxnDef }
     * 
     */
    public ArrayOfTxnDef createArrayOfTxnDef() {
        return new ArrayOfTxnDef();
    }

    /**
     * Create an instance of {@link TxnDef }
     * 
     */
    public TxnDef createTxnDef() {
        return new TxnDef();
    }

    /**
     * Create an instance of {@link ArrayOfGetCardRestrictionInfo }
     * 
     */
    public ArrayOfGetCardRestrictionInfo createArrayOfGetCardRestrictionInfo() {
        return new ArrayOfGetCardRestrictionInfo();
    }

    /**
     * Create an instance of {@link GetCardRestrictionInfo2 }
     * 
     */
    public GetCardRestrictionInfo2 createGetCardRestrictionInfo2() {
        return new GetCardRestrictionInfo2();
    }

    /**
     * Create an instance of {@link ArrayOfCardTxnFeeProfileInfo }
     * 
     */
    public ArrayOfCardTxnFeeProfileInfo createArrayOfCardTxnFeeProfileInfo() {
        return new ArrayOfCardTxnFeeProfileInfo();
    }

    /**
     * Create an instance of {@link CardTxnFeeProfileInfo }
     * 
     */
    public CardTxnFeeProfileInfo createCardTxnFeeProfileInfo() {
        return new CardTxnFeeProfileInfo();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link UsedLimitDetail }
     * 
     */
    public UsedLimitDetail createUsedLimitDetail() {
        return new UsedLimitDetail();
    }

    /**
     * Create an instance of {@link ArrayOfLimitDetail }
     * 
     */
    public ArrayOfLimitDetail createArrayOfLimitDetail() {
        return new ArrayOfLimitDetail();
    }

    /**
     * Create an instance of {@link LimitDetail }
     * 
     */
    public LimitDetail createLimitDetail() {
        return new LimitDetail();
    }

    /**
     * Create an instance of {@link BalanceDetail }
     * 
     */
    public BalanceDetail createBalanceDetail() {
        return new BalanceDetail();
    }

    /**
     * Create an instance of {@link RealCardLimitDetail }
     * 
     */
    public RealCardLimitDetail createRealCardLimitDetail() {
        return new RealCardLimitDetail();
    }

    /**
     * Create an instance of {@link CardLevelLimitsRequest }
     * 
     */
    public CardLevelLimitsRequest createCardLevelLimitsRequest() {
        return new CardLevelLimitsRequest();
    }

    /**
     * Create an instance of {@link CstCompanyAddress }
     * 
     */
    public CstCompanyAddress createCstCompanyAddress() {
        return new CstCompanyAddress();
    }

    /**
     * Create an instance of {@link ArrayOfLong2 }
     * 
     */
    public ArrayOfLong2 createArrayOfLong2() {
        return new ArrayOfLong2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SWSessionInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SWSessionInfo }{@code >}
     */
    @XmlElementDecl(namespace = "Smartsoft.Integration.Services", name = "SWSessionInfo")
    public JAXBElement<SWSessionInfo> createSWSessionInfo(SWSessionInfo value) {
        return new JAXBElement<SWSessionInfo>(_SWSessionInfo_QNAME, SWSessionInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "Smartsoft.Integration.Services", name = "PhoneWorkExtension", scope = CustomerInfo.class)
    public JAXBElement<Integer> createCustomerInfoPhoneWorkExtension(Integer value) {
        return new JAXBElement<Integer>(_CustomerInfoPhoneWorkExtension_QNAME, Integer.class, CustomerInfo.class, value);
    }

}
