//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.02 at 10:11:22 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemDatabase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SystemDatabase"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PRODUCTION"/&gt;
 *     &lt;enumeration value="ARCHIEVE"/&gt;
 *     &lt;enumeration value="HISTORY"/&gt;
 *     &lt;enumeration value="CBSLIVE"/&gt;
 *     &lt;enumeration value="MISLIVE"/&gt;
 *     &lt;enumeration value="POSTOFFICE"/&gt;
 *     &lt;enumeration value="MERCHANT"/&gt;
 *     &lt;enumeration value="PAYMENT_SYSTEM"/&gt;
 *     &lt;enumeration value="CROPPER"/&gt;
 *     &lt;enumeration value="OWLIVE"/&gt;
 *     &lt;enumeration value="DEPLOYMENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SystemDatabase", namespace = "SWSharedTypes")
@XmlEnum
public enum SystemDatabase {

    PRODUCTION,
    ARCHIEVE,
    HISTORY,
    CBSLIVE,
    MISLIVE,
    POSTOFFICE,
    MERCHANT,
    PAYMENT_SYSTEM,
    CROPPER,
    OWLIVE,
    DEPLOYMENT;

    public String value() {
        return name();
    }

    public static SystemDatabase fromValue(String v) {
        return valueOf(v);
    }

}
