//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.29 at 09:00:37 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TopupToPrepaidObj complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TopupToPrepaidObj"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AllowedProcessChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BalanceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BarcodeNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InsertChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ShowInStmt" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="SlipNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StmtMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TxnAmnt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="TxnCurrCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TxnStt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TxnTrm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SrcRefId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Otc" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Ots" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Ote" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="IbanNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TopupToPrepaidObj", propOrder = {
    "allowedProcessChannel",
    "balanceType",
    "cardNo",
    "barcodeNo",
    "insertChannel",
    "showInStmt",
    "slipNo",
    "stmtMsg",
    "transactionType",
    "txnAmnt",
    "txnCurrCode",
    "txnStt",
    "txnTrm",
    "srcRefId",
    "otc",
    "ots",
    "ote",
    "ibanNo"
})
public class TopupToPrepaidObj {

    @XmlElement(name = "AllowedProcessChannel")
    protected String allowedProcessChannel;
    @XmlElement(name = "BalanceType")
    protected String balanceType;
    @XmlElement(name = "CardNo")
    protected String cardNo;
    @XmlElement(name = "BarcodeNo")
    protected String barcodeNo;
    @XmlElement(name = "InsertChannel")
    protected String insertChannel;
    @XmlElement(name = "ShowInStmt", required = true, type = Boolean.class, nillable = true)
    protected Boolean showInStmt;
    @XmlElement(name = "SlipNo")
    protected String slipNo;
    @XmlElement(name = "StmtMsg")
    protected String stmtMsg;
    @XmlElement(name = "TransactionType")
    protected String transactionType;
    @XmlElement(name = "TxnAmnt", required = true, nillable = true)
    protected BigDecimal txnAmnt;
    @XmlElement(name = "TxnCurrCode", required = true, type = Integer.class, nillable = true)
    protected Integer txnCurrCode;
    @XmlElement(name = "TxnStt")
    protected String txnStt;
    @XmlElement(name = "TxnTrm")
    protected String txnTrm;
    @XmlElement(name = "SrcRefId")
    protected String srcRefId;
    @XmlElement(name = "Otc")
    protected short otc;
    @XmlElement(name = "Ots")
    protected short ots;
    @XmlElement(name = "Ote")
    protected short ote;
    @XmlElement(name = "IbanNo")
    protected String ibanNo;

    /**
     * Gets the value of the allowedProcessChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowedProcessChannel() {
        return allowedProcessChannel;
    }

    /**
     * Sets the value of the allowedProcessChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowedProcessChannel(String value) {
        this.allowedProcessChannel = value;
    }

    /**
     * Gets the value of the balanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceType() {
        return balanceType;
    }

    /**
     * Sets the value of the balanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceType(String value) {
        this.balanceType = value;
    }

    /**
     * Gets the value of the cardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * Sets the value of the cardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNo(String value) {
        this.cardNo = value;
    }

    /**
     * Gets the value of the barcodeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcodeNo() {
        return barcodeNo;
    }

    /**
     * Sets the value of the barcodeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcodeNo(String value) {
        this.barcodeNo = value;
    }

    /**
     * Gets the value of the insertChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertChannel() {
        return insertChannel;
    }

    /**
     * Sets the value of the insertChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertChannel(String value) {
        this.insertChannel = value;
    }

    /**
     * Gets the value of the showInStmt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowInStmt() {
        return showInStmt;
    }

    /**
     * Sets the value of the showInStmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowInStmt(Boolean value) {
        this.showInStmt = value;
    }

    /**
     * Gets the value of the slipNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlipNo() {
        return slipNo;
    }

    /**
     * Sets the value of the slipNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlipNo(String value) {
        this.slipNo = value;
    }

    /**
     * Gets the value of the stmtMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStmtMsg() {
        return stmtMsg;
    }

    /**
     * Sets the value of the stmtMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStmtMsg(String value) {
        this.stmtMsg = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the txnAmnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTxnAmnt() {
        return txnAmnt;
    }

    /**
     * Sets the value of the txnAmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTxnAmnt(BigDecimal value) {
        this.txnAmnt = value;
    }

    /**
     * Gets the value of the txnCurrCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTxnCurrCode() {
        return txnCurrCode;
    }

    /**
     * Sets the value of the txnCurrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTxnCurrCode(Integer value) {
        this.txnCurrCode = value;
    }

    /**
     * Gets the value of the txnStt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnStt() {
        return txnStt;
    }

    /**
     * Sets the value of the txnStt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnStt(String value) {
        this.txnStt = value;
    }

    /**
     * Gets the value of the txnTrm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnTrm() {
        return txnTrm;
    }

    /**
     * Sets the value of the txnTrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnTrm(String value) {
        this.txnTrm = value;
    }

    /**
     * Gets the value of the srcRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcRefId() {
        return srcRefId;
    }

    /**
     * Sets the value of the srcRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcRefId(String value) {
        this.srcRefId = value;
    }

    /**
     * Gets the value of the otc property.
     * 
     */
    public short getOtc() {
        return otc;
    }

    /**
     * Sets the value of the otc property.
     * 
     */
    public void setOtc(short value) {
        this.otc = value;
    }

    /**
     * Gets the value of the ots property.
     * 
     */
    public short getOts() {
        return ots;
    }

    /**
     * Sets the value of the ots property.
     * 
     */
    public void setOts(short value) {
        this.ots = value;
    }

    /**
     * Gets the value of the ote property.
     * 
     */
    public short getOte() {
        return ote;
    }

    /**
     * Sets the value of the ote property.
     * 
     */
    public void setOte(short value) {
        this.ote = value;
    }

    /**
     * Gets the value of the ibanNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIbanNo() {
        return ibanNo;
    }

    /**
     * Sets the value of the ibanNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIbanNo(String value) {
        this.ibanNo = value;
    }

}
