//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.02 at 10:11:22 AM IST 
//


package com.mycardsolutions.webservice.soapdto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cardNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="otc" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ots" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="txnAmnt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardNo",
    "otc",
    "ots",
    "txnAmnt"
})
@XmlRootElement(name = "TransactionFeeCalculation")
public class TransactionFeeCalculation {

    protected String cardNo;
    protected int otc;
    protected int ots;
    @XmlElement(required = true)
    protected BigDecimal txnAmnt;

    /**
     * Gets the value of the cardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * Sets the value of the cardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNo(String value) {
        this.cardNo = value;
    }

    /**
     * Gets the value of the otc property.
     * 
     */
    public int getOtc() {
        return otc;
    }

    /**
     * Sets the value of the otc property.
     * 
     */
    public void setOtc(int value) {
        this.otc = value;
    }

    /**
     * Gets the value of the ots property.
     * 
     */
    public int getOts() {
        return ots;
    }

    /**
     * Sets the value of the ots property.
     * 
     */
    public void setOts(int value) {
        this.ots = value;
    }

    /**
     * Gets the value of the txnAmnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTxnAmnt() {
        return txnAmnt;
    }

    /**
     * Sets the value of the txnAmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTxnAmnt(BigDecimal value) {
        this.txnAmnt = value;
    }

}
