//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.21 at 09:26:50 PM IST 
//


package com.mycardsolutions.webservice.soapdto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionFeeCalculationResult" type="{Smartsoft.Integration.Services}ServiceResponse" minOccurs="0"/&gt;
 *         &lt;element name="feeAmnt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionFeeCalculationResult",
    "feeAmnt"
})
@XmlRootElement(name = "TransactionFeeCalculationResponse")
public class TransactionFeeCalculationResponse {

    @XmlElement(name = "TransactionFeeCalculationResult")
    protected ServiceResponse transactionFeeCalculationResult;
    @XmlElement(required = true)
    protected BigDecimal feeAmnt;

    /**
     * Gets the value of the transactionFeeCalculationResult property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceResponse }
     *     
     */
    public ServiceResponse getTransactionFeeCalculationResult() {
        return transactionFeeCalculationResult;
    }

    /**
     * Sets the value of the transactionFeeCalculationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceResponse }
     *     
     */
    public void setTransactionFeeCalculationResult(ServiceResponse value) {
        this.transactionFeeCalculationResult = value;
    }

    /**
     * Gets the value of the feeAmnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFeeAmnt() {
        return feeAmnt;
    }

    /**
     * Sets the value of the feeAmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFeeAmnt(BigDecimal value) {
        this.feeAmnt = value;
    }

}
